json.extract! job, :id,
                   :description,
                   :job_type,
                   :status,
                   :address,
                   :duration,
                   :wage,
                   :start_time,
                   :cost,
                   :lat,
                   :lng,
                   :worker_id
